project:
  type: website

website:
  title: "Nicola C Anderson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Resume"
        href: ncca_resume.pdf
        icon: link-45deg

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

execute:
  freeze: auto

