project:
  type: website

website:
  title: "Nicola C Anderson"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: vapor
    css: styles.css
    toc: true

execute:
  freeze: auto

